<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="124060" started-at="2017-09-13T16:36:00Z" finished-at="2017-09-13T16:38:04Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="124060" started-at="2017-09-13T16:36:00Z" finished-at="2017-09-13T16:38:04Z">
      <class name="com.TestSuite.CuramDriver">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.TestSuite.CuramDriver@643b1d11]" name="beforeMethod" is-config="true" duration-ms="6" started-at="2017-09-13T12:36:00Z" finished-at="2017-09-13T12:36:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="f()[pri:0, instance:com.TestSuite.CuramDriver@643b1d11]" name="f" duration-ms="124034" started-at="2017-09-13T12:36:00Z" finished-at="2017-09-13T12:38:04Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[An unexpected exception occured.
com.selenium.SafeActions.safeClearAndType(SafeActions.java:220)
com.pageFunctions.moreabtufunc.AddionalInfo(moreabtufunc.java:74)
com.TestSuite.New3HHApp.FirstMemberDetails(New3HHApp.java:448)
com.TestSuite.New3HHApp.TC1035(New3HHApp.java:216)
com.TestSuite.CuramDriver.CheckTCID(CuramDriver.java:72)
com.TestSuite.CuramDriver.f(CuramDriver.java:33)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
java.lang.reflect.Method.invoke(Unknown Source)
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
org.testng.TestRunner.privateRun(TestRunner.java:773)
org.testng.TestRunner.run(TestRunner.java:623)
org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
org.testng.SuiteRunner.run(SuiteRunner.java:259)
org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
org.testng.TestNG.run(TestNG.java:1018)
org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: An unexpected exception occured.
com.selenium.SafeActions.safeClearAndType(SafeActions.java:220)
com.pageFunctions.moreabtufunc.AddionalInfo(moreabtufunc.java:74)
com.TestSuite.New3HHApp.FirstMemberDetails(New3HHApp.java:448)
com.TestSuite.New3HHApp.TC1035(New3HHApp.java:216)
com.TestSuite.CuramDriver.CheckTCID(CuramDriver.java:72)
com.TestSuite.CuramDriver.f(CuramDriver.java:33)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
java.lang.reflect.Method.invoke(Unknown Source)
org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
org.testng.TestRunner.privateRun(TestRunner.java:773)
org.testng.TestRunner.run(TestRunner.java:623)
org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
org.testng.SuiteRunner.run(SuiteRunner.java:259)
org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
org.testng.TestNG.run(TestNG.java:1018)
org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
	at com.testng.Assert.fail(Assert.java:199)
	at com.selenium.SafeActions.safeClearAndType(SafeActions.java:220)
	at com.pageFunctions.moreabtufunc.AddionalInfo(moreabtufunc.java:74)
	at com.TestSuite.New3HHApp.FirstMemberDetails(New3HHApp.java:448)
	at com.TestSuite.New3HHApp.TC1035(New3HHApp.java:216)
	at com.TestSuite.CuramDriver.CheckTCID(CuramDriver.java:72)
	at com.TestSuite.CuramDriver.f(CuramDriver.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
      </class> <!-- com.TestSuite.CuramDriver -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
